name: Deploy Published Image
on:
  registry_package:
    types: [published,updated]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - run: cd /srv/docker/ccinvoice
      - run: docker compose pull && docker compose up -d --force-recreate
